# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Language of the webpage
lang: es

# Timezone
timezone: Europe/Madrid

# jekyll-seo-tag settings
title: Iván Rodríguez Díaz # the main title
tagline: Portafolio de proyectos Audiovisuales # it will display as the subtitle
description: >- # used by seo meta and the atom feed
  AAAAA

# URL of the site
url: "https://ivanrodriguez14.github.io"

# GitHub settings
github:
  username: IvanRodriguez14 # change to your GitHub username

# Twitter settings
twitter:
  username: twitter_username # change to your Twitter username

# Social Links
social:
  name: Iván Rodríguez Díaz
  email: ivan.rodriguez.d.14@gmail.com # change to your email address
  links: 
    - https://github.com/IvanRodriguez14
    - https://www.linkedin.com/in/ivan-rodriguez-diaz # Linkedin

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID

# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Theme mode
theme_mode: # light / dark

# CDN (optional)
cdn:

# Avatar for the sidebar
avatar: "assets/images/FOTO_CV.png"

# Social preview image for SEO
social_preview_image: # string, local or CORS resources

# Table of contents settings
toc: true

# Comments settings
comments:
  provider: # [disqus | utterances | giscus]
  disqus:
    shortname: # fill with the Disqus shortname

# PWA (Progressive Web App) settings
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      # - "/example"

# Pagination settings
paginate: 10

# Base URL (leave blank if the site is at the root)
baseurl: ""

# Jekyll configurations
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # All files in the project
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
